name: Build Project

on: [push]  

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install MSYS2 and MinGW
      uses: msys2/setup-msys2@v2
      with:
        architecture: 'x86_64'
        pacman_packages: |
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-make
        update: false

    - name: Build the project
      run: |
        cmake -G "MinGW Makefiles" -Bbuild -DCMAKE_BUILD_TYPE=Release
        cmake --build build
